function [ splineData ] = constructEmptySplinedata
% Create an empty splineData struct

splineData = struct('nS',[],...
    'nT',[],...
    'nPhi',[],...
    'N',[],...
    'Nt',[],...
    'Nphi',[],...
    'quadDegree',[],...
    'dSpace',[],...
    'phiEps','1e-12',...
    'a',[1 0 1],...
    'knotsS',[],...
    'knotsT',[],...
    'knotsPhi',[],...
    'innerKnotsS',[],...
    'innerKnotsT',[],...
    'innerKnotsPhi',[],...
    'periodic',1);

end

