%% constructEmptySplineData
%
% Function constructs a splineData struct. Some default parameters
% are being set; others are set to empty arrays.
%
% Default parameters
%   dSpace = 2
%   phiEps = 1e-12
%
% Output
%   splineData
%       The created struct.
%
function [ splineData ] = constructSplineData

splineData = struct(...
    'a', [0 0 0 0 0], ...
    'N', [], ...
    'nS', 3, ...
    'Nt', 10, ...
    'nT', 2, ...
    'curveClosed', 0, ...
    'scaleInv', 0, ...
    'quadDegree', [6 4], ...
    'dSpace', 2, ...
    'stepsT', [], ...
    'varData', [], ...
    'knots', [], ...
    'quadData', [], ...
    'quadDataTensor', [],...
    'nPhi',[],...
    'Nphi',[],...
    'interpolS',[],...
    'lengthWeighted', 0);
end

